 {% set name = "xmsgeom" %}
{% set version = "1.0.0" %}
{% set sha256 = "94c38569578c1479c65a6ff712d9e61c0e6030c633f4e0ee4b42cff9930984c3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python =3.6
    - cmake >=3.0.0
    - boost =1.67
    - cxxtest >=4.0.0
    - pybind11 >=2.2.2
    - xmscore >=1.0.40
  run:
    - python =3.6
    - xmscore >=1.0.40
    - numpy

test:
  source_files:
    - xmsgeom/python/*.py
    - xmsgeom/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./xmsgeom/python
  imports:
    - xmsgeom_py
    - numpy
  requires:
    - xmscore

about:
  home: aquaveo.com
  license: XMSNG
  license_file: LICENSE
  summary: 'Geometry library with for xms.'
  doc_url: 'https://aquaveo.github.io/xmsgeom/'
  dev_url: 'https://github.com/Aquaveo/xmsgeom'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
