# The language in this case has no bearing - we are going to be making use of conda.
language: generic

osx: &osx
  os: osx

script:
    # Remove homebrew.
  - echo ""
  - echo "Removing homebrew from Travis CI to avoid conflicts."
  - curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
  - chmod +x ~/uninstall_homebrew
  - ~/uninstall_homebrew -fq
  - rm ~/uninstall_homebrew

    # Install Miniconda.
  - echo ""
  - echo "Installing a fresh version of Miniconda."
  - curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > ~/miniconda.sh
  - bash ~/miniconda.sh -b -p ~/miniconda
  - source ~/miniconda/bin/activate root

    # Configure conda.
  - echo ""
  - echo "Configuring conda."
  - conda config --add channels conda-forge
  - conda config --set show_channel_urls true
  - conda install --yes --quiet conda-forge-ci-setup=1.* conda-forge-pinning networkx
  - source run_conda_forge_build_setup

    # We just want to build all of the recipes.
  - python .ci_support/build_all.py ./recipes

jobs:
   include:
     - <<: *osx
       osx_image: xcode9.2
       env: CONAN_APPLE_CLANG_VERSIONS=9.0 XMS_RUN_TESTS=1
