# The language in this case has no bearing - we are going to be making use of conda.

script:
    # Remove homebrew.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "";
      echo "Removing homebrew from Travis CI to avoid conflicts.";
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew;
      chmod +x ~/uninstall_homebrew;
      ~/uninstall_homebrew -fq;
      rm ~/uninstall_homebrew;
    fi

    # Install Miniconda.
  - echo ""
  - echo "Installing a fresh version of Miniconda."
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > ~/miniconda.sh;
    else
      curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > ~/miniconda.sh;
    fi
  - bash ~/miniconda.sh -b -p ~/miniconda
  - source ~/miniconda/bin/activate root

    # Configure conda.
  - echo "Configuring conda."
  - conda config --add channels aquaveo
  - conda config --set show_channel_urls true
  - conda install --yes --quiet networkx conda-build jinja2 anaconda-client

    # Copy or link files to necissary locations
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      sudo ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk /opt/MacOSX10.9.sdk;
    else
      sudo cp ~/miniconda/x86_64-conda_cos6-linux-gnu/sysroot/lib/libstdc++.so /usr/lib/x86_64-linux-gnu/libstdc++.so.6;
    fi

    # We just want to build all of the recipes.
  - conda build recipes/* --token ${CI_CONDA_TOKEN}

env:
  global: 
    - XMS_RUN_TESTS=1
    - CPU_COUNT=2
    - PYTHONUNBUFFERED=1
    - MACOSX_DEPLOYMENT_TARGET="10.9"

matrix:
  include:
    - os: linux
      sudo: required
      language: python
      python: "3.6"
      services:
        - docker
    - os: osx
      language: generic
      osx_image: xcode6.4

