# The language in this case has no bearing - we are going to be making use of conda.
language: generic

os:
  - linux
    env: XMS_RUN_TESTS=1
  - osx
    osx_image: xcode6.4
    env: XMS_RUN_TESTS=1

script:
    # Remove homebrew.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    echo ""
    echo "Removing homebrew from Travis CI to avoid conflicts."
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
    chmod +x ~/uninstall_homebrew
    ~/uninstall_homebrew -fq
    rm ~/uninstall_homebrew
    fi

    # Install Miniconda.
  - echo ""
  - echo "Installing a fresh version of Miniconda."
  - curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > ~/miniconda.sh
  - bash ~/miniconda.sh -b -p ~/miniconda
  - source ~/miniconda/bin/activate root

    # Configure conda.
  - echo ""
  - echo "Configuring conda."
  - conda config --add channels conda-forge
  - conda config --set show_channel_urls true
  - conda install --yes --quiet conda-forge-ci-setup=1.* conda-forge-pinning networkx
  - source run_conda_forge_build_setup

    # We just want to build all of the recipes.
  - python .ci_support/build_all.py ./recipes
