 {% set name = "xmsgrid" %}
{% set version = "2.0.0" %}
{% set sha256 = "7e10594ce8f4dc25a9ac5fe7ec0143ad62f06b4ba6cd1ea0d8f801490fa2fa15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  string: py{{ python }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - python {{ python }}
    - cmake >=3.0.0
    - boost =1.67
    - pybind11 >=2.2.2
    - xmscore 2.*
  run:
    - python {{ python }}
    - xmscore 2.*
    - numpy

test:
  source_files:
    - xmsgrid/python/*.py
    - xmsgrid/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./xmsgrid/python
  imports:
    - xmsgrid
    - numpy

about:
  home: aquaveo.com
  license: BSD2
  license_file: LICENSE
  summary: 'Grid library with for xms.'
  doc_url: 'https://aquaveo.github.io/xmsgrid/'
  dev_url: 'https://github.com/Aquaveo/xmsgrid'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
