 {% set name = "xmsgrid" %}
{% set version = "1.0.11" %}
{% set sha256 = "8be6e25e01ba390b9a152a4f05d9fd192bd3009c3d46c9c4a2e0493159a85712" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python =3.6
    - cmake >=3.0.0
    - boost =1.67
    - cxxtest >=4.0.0
    - pybind11 >=2.2.2
    - xmscore >=1.0.40
  run:
    - python =3.6
    - xmscore >=1.0.40
    - numpy

test:
  source_files:
    - xmsgrid/python/*.py
    - xmsgrid/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./xmsgrid/python
  imports:
    - xmsgrid_py
    - numpy
  requires:
    - xmscore

about:
  home: aquaveo.com
  license: XMSNG
  license_file: LICENSE
  summary: 'Grid library with for xms.'
  doc_url: 'https://aquaveo.github.io/xmsgrid/'
  dev_url: 'https://github.com/Aquaveo/xmsgrid'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
