 {% set name = "xmsgrid" %}
{% set version = "1.0.2" %}
{% set sha256 = "d65caa42c3e3e8784e3ca59037843e648dac24f6ec5d3b2f2ebb94387af8246b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python =3.6
    - cmake >=3.0.0
    - boost =1.65.1
    - cxxtest >=4.0.0
    - pybind11 >=2.2.2
    - xmscore >=1.0.24
  run:
    - python =3.6
    - numpy

test:
  source_files:
    - xmsgrid/python/*.py
    - xmsgrid/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./xmsgrid/python
  import:
    - xmsgrid_py
    - numpy
  requires:
    - xmscore

about:
  home: aquaveo.com
  license: XMSNG
  license_file: LICENSE
  summary: 'Grid library with for xms.'
  doc_url: 'https://aquaveo.github.io/xmsgrid/'
  dev_url: 'https://github.com/Aquaveo/xmsgrid'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
