 {% set name = "xmsgrid" %}
{% set version = "1.0.8" %}
{% set sha256 = "b05fb566d651ab9ef19aa9a83ff79801c0c3298493cce13419094f9d6e73fd4e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python =3.6
    - cmake >=3.0.0
    - boost =1.65.1
    - cxxtest >=4.0.0
    - pybind11 >=2.2.2
    - xmscore >=1.0.24
  run:
    - python =3.6
    - numpy

test:
  source_files:
    - xmsgrid/python/*.py
    - xmsgrid/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./xmsgrid/python
  import:
    - xmsgrid_py
    - numpy
  requires:
    - xmscore

about:
  home: aquaveo.com
  license: XMSNG
  license_file: LICENSE
  summary: 'Interpolation library with for xms.'
  doc_url: 'https://aquaveo.github.io/xmsgrid/'
  dev_url: 'https://github.com/Aquaveo/xmsgrid'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
