version: 2


jobs:
  build:
    working_directory: ~/test
    machine: true
    steps:
      - checkout

      - run:
          name: Install and Configure Conda
          command: |
            chmod +x ./.circleci/install_and_configure.sh
            /bin/bash ./.circleci/install_and_configure.sh

      - run:
          name: Pull Docker Image
          command: |
            docker pull condaforge/linux-anvil

      - run:
          name: Build Conda Packages
          command: |
            ./circleci/run_docker_build.sh