{% set name = "xmsstamper" %}
{% set version = "3.0.0" %}
{% set sha256 = "70839b5ddeabdc04b9be088a4d3e35bddd410ced61493d5099e1cc62eed7412b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  string: py{{ python }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - python {{ python }}
    - cmake >=3.0.0
    - boost =1.67
    - pybind11 >=2.2.2
    - xmscore 2.*
    - xmsinterp 2.*
  run:
    - python {{ python }}
    - numpy
    - xmscore 2.*
    - xmsinterp 2.*

test:
  source_files:
    - test_files/*
    - xmsstamper/python/*.py
    - xmsstamper/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./xmsstamper/python
  imports:
    - xmsstamper
    - numpy

about:
  home: aquaveo.com
  license: BSD2
  license_file: LICENSE
  summary: 'Stamping library with for xms.'
  doc_url: 'https://aquaveo.github.io/xmsstamper/'
  dev_url: 'https://github.com/Aquaveo/xmsstamper'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
