 {% set name = "xmsextractor" %}
{% set version = "1.0.0" %}
{% set sha256 = "2dc11f97e0d33b5eb18998b680ca178821723041f4fde8c0a107defddef8b47b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python =3.6
    - cmake >=3.0.0
    - boost =1.67
    - cxxtest >=4.0.0
    - pybind11 >=2.2.2
    - xmscore >=1.0.40
    - xmsinterp >=1.0.18
    - xmsgrid >=1.0.10
  run:
    - python =3.6
    - numpy

test:
  source_files:
    - xmsextractor/python/*.py
    - xmsextractor/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./extractor/python
  imports:
    - xmsextractor_py
    - numpy
  requires:
    - xmscore
    - xmsinterp
    - xmsgrid

about:
  home: aquaveo.com
  license: XMSNG
  license_file: LICENSE
  summary: 'Extractor library with for xms.'
  doc_url: 'https://aquaveo.github.io/xmsextractor/'
  dev_url: 'https://github.com/Aquaveo/xmsextractor'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
