 {% set name = "xmsextractor" %}
{% set version = "2.0.0" %}
{% set sha256 = "98ee31071b915de74e4fb208940141abd721bbe33a661b3c61a13adc53cbc86c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  string: py{{ python }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - python {{ python }}
    - cmake >=3.0.0
    - boost =1.67
    - pybind11 >=2.2.2
    - xmscore 2.*
    - xmsinterp 2.*
    - xmsgrid 2.*
  run:
    - python {{ python }}
    - xmscore 2.*
    - xmsinterp 2.*
    - xmsgrid 2.*
    - numpy

test:
  source_files:
    - xmsextractor/python/*.py
    - xmsextractor/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./xmsextractor/python
  imports:
    - xmsextractor
    - numpy

about:
  home: aquaveo.com
  license: BSD2
  license_file: LICENSE
  summary: 'Extractor library with for xms.'
  doc_url: 'https://aquaveo.github.io/xmsextractor/'
  dev_url: 'https://github.com/Aquaveo/xmsextractor'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
