{% set name = "xmsinterp" %}
{% set version = "1.0.21" %}
{% set sha256 = "81808d1e4a259ea657cb102218592aa40bf7299a4e25b7dd95bc13b98bed69da" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python =3.6
    - cmake >=3.0.0
    - boost =1.67
    - cxxtest >=4.0.0
    - pybind11 >=2.2.2
    - xmscore >=1.0.40
  run:
    - python =3.6
    - xmscore >=1.0.40
    - numpy

test:
  source_files:
    - xmsinterp/python/*.py
    - xmsinterp/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./xmsinterp/python
  imports:
    - xmsinterp_py
    - numpy
  requires:
    - xmscore

about:
  home: aquaveo.com
  license: XMSNG
  license_file: LICENSE
  summary: 'Interpolation library with for xms.'
  doc_url: 'https://aquaveo.github.io/xmsinterp/'
  dev_url: 'https://github.com/Aquaveo/xmsinterp'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
