{% set name = "xmsinterp" %}
{% set version = "1.0.14" %}
{% set sha256 = "7b8df89773484bd35231703e30f8c041fc7b2720634a9bb6489cd6d11983da7d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python =3.6
    - cmake >=3.0.0
    - boost =1.65.1
    - cxxtest >=4.0.0
    - pybind11 >=2.2.2
    - xmscore >=1.0.28
  run:
    - python =3.6
    - numpy

test:
  source_files:
    - xmsinterp/python/*.py
    - xmsinterp/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./xmsinterp/python
  import:
    - xmsinterp_py
    - numpy
  requires:
    - xmscore

about:
  home: aquaveo.com
  license: XMSNG
  license_file: LICENSE
  summary: 'Interpolation library with for xms.'
  doc_url: 'https://aquaveo.github.io/xmsinterp/'
  dev_url: 'https://github.com/Aquaveo/xmsinterp'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
