{% set name = "xmsinterp" %}
{% set version = "1.0.7" %}
{% set sha256 = "8011bcd43289abd3ac140905b4d823306ca28576a2939d00e7f2d95cb6e947be" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - cmake >=3.0.0
    - boost =1.65.1
    - cxxtest >=4.0.0
    - pybind11 >=2.2.2
    - xmscore >=1.0.19
  run:
    - python
    - numpy

test:
  source_files:
    - build/runner{% if win %}.exe{% endif %}
    - build/xmsinterp_py.cpython*
    - xmsinterp/python/*.py
    - xmsinterp/python/**/*.py
  commands:
    - {% if unix %}build/runner{% else %}build\runner{% endif %}
    - cd build
    - python -m unittest discover -v -p *_pyt.py -s ../xmsinterp/python
  import:
    - xmsinterp_py
    - numpy

about:
  home: aquaveo.com
  license: XMSNG
  license_file: LICENSE
  summary: 'Interpolation library with for xms.'
  doc_url: 'https://aquaveo.github.io/xmsinterp/'
  dev_url: 'https://github.com/Aquaveo/xmsinterp'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
