 {% set name = "xmsgridtrace" %}
{% set version = "1.0.2" %}
{% set sha256 = "bee064565f012d401699e38417fb0741f98922b1ee5450fd0683da1b2e5ff2a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python =3.6
    - cmake >=3.0.0
    - boost =1.67
    - cxxtest >=4.0.0
    - pybind11 >=2.2.2
    - xmscore >=1.0.40
    - xmsinterp >=1.0.18
    - xmsgrid >=1.0.10
    - xmsextractor >=1.0.0
  run:
    - python =3.6
    - xmscore >=1.0.40
    - xmsinterp >=1.0.18
    - xmsgrid >=1.0.10
    - xmsextractor >=1.0.0
    - numpy

test:
  source_files:
    - xmsgridtrace/python/*.py
    - xmsgridtrace/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./xmsgridtrace/python
  imports:
    - xmsgridtrace_py
    - numpy
  requires:
    - xmscore
    - xmsinterp
    - xmsgrid
    - xmsextractor

about:
  home: aquaveo.com
  license: XMSNG
  license_file: LICENSE
  summary: 'Grid Trace library with for xms.'
  doc_url: 'https://aquaveo.github.io/xmsgridtrace/'
  dev_url: 'https://github.com/Aquaveo/xmsextractor'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
