{% set name = "xmsmesh" %}
{% set version = "0.0.1" %}
{% set sha256 = "6c52fc5c618e6472f2bbd211eb8b54448b389ed78b287d22640f074cc521a881" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
   fn: {{ name }}-{{ version }}.tar.gz
   url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
   sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python =3.6.5
    - cmake >=3.0.0
    - boost =1.65.1
    - cxxtest >=4.0.0
    - pybind11 >=2.2.2
    - xmscore >=1.0.28
    - xmsinterp >=1.0.8
  run:
    - python =3.6.5
    - numpy

test:
  source_files:
    - xmsmesh/python/*.py
    - xmsmesh/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./xmsmesh/python
  import:
    - xmsmesh_py
    - xmsinterp_py
    - numpy
  requires:
    - xmscore >=1.0.28
    - xmsinterp >=1.0.8

about:
  home: aquaveo.com
  license: XMSNG
  license_file: LICENSE
  summary: 'Meshing library with for xms.'
  doc_url: 'https://aquaveo.github.io/xmsmesh/'
  dev_url: 'https://github.com/Aquaveo/xmsmesh'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
