{% set name = "xmsmesh" %}
{% set version = "2.0.0" %}
{% set sha256 = "9e79661d61739da074766190cccceac70988740d6e7a9b13d710a2ecdaf928c7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
   fn: {{ name }}-{{ version }}.tar.gz
   url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
   sha256: {{ sha256 }}

build:
  number: 0
  string: py{{ python }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - python {{ python }}
    - cmake >=3.0.0
    - boost =1.65.1
    - pybind11 >=2.2.2
    - xmscore 2.*
    - xmsinterp 2.*
    - xmsgrid 2.*
  run:
    - python {{ python }}
    - xmscore 2.*
    - xmsinterp 2.*
    - xmsgrid 2.*
    - numpy

test:
  source_files:
    - xmsmesh/python/*.py
    - xmsmesh/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./xmsmesh/python
  import:
    - xmsmesh_
    - numpy

about:
  home: aquaveo.com
  license: BSD2
  license_file: LICENSE
  summary: 'Meshing library with for xms.'
  doc_url: 'https://aquaveo.github.io/xmsmesh/'
  dev_url: 'https://github.com/Aquaveo/xmsmesh'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
