{% set name = "xmscore" %}
{% set version = "1.0.43" %}
{% set sha256 = "4cc32eab710bfa96731323948673f094444717d7f23282383b287c977392cbf4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python =3.6
    - cmake >=3.0.0
    - boost =1.67
    - cxxtest >=4.0.0
    - pybind11 >=2.2.2
  run:
    - python =3.6
    - numpy

test:
  source_files:
    - xmscore/python/*.py
    - xmscore/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./xmscore/python
  imports:
    - xmscore_py


about:
  home: aquaveo.com
  license: XMSNG
  license_file: LICENSE
  summary: 'Support library for all XMS libraries and products.'
  doc_url: 'https://aquaveo.github.io/xmscore/'
  dev_url: 'https://github.com/Aquaveo/xmscore'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
