{% set name = "xmscore" %}
{% set version = "1.0.20" %}
{% set sha256 = "c0e36ee3e74c9d862914cbddf279c2c4f1c32b7e723aad8a43b0e8636d382db6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python >3
    - cmake >=3.0.0
    - boost =1.65.1
    - cxxtest >=4.0.0
  run:
    - libgcc

test:
  source_files:
    - build/runner{% if win %}.exe{% endif %}
  commands:
    - {% if unix %}build/runner{% else %}build\runner{% endif %}

about:
  home: aquaveo.com
  license: XMSNG
  license_file: LICENSE
  summary: 'Support library for XMS libraries and products.'
  doc_url: 'https://aquaveo.github.io/xmscore/'
  dev_url: 'https://github.com/Aquaveo/xmscore'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
