{% set name = "xmscore" %}
{% set version = "2.0.1" %}
{% set sha256 = "b27549bb453e00eb0dbc60b3354c485dfad22274113ef3d7fa599816178cb421" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Aquaveo/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python {{ python }}
    - cmake >=3.0.0
    - boost =1.67
    - pybind11 >=2.2.2
  run:
    - python {{ python }}
    - numpy

test:
  source_files:
    - xmscore/python/*.py
    - xmscore/python/**/*.py
  commands:
    - python -m unittest discover -v -p *_pyt.py -s ./xmscore/python
  imports:
    - xmscore


about:
  home: aquaveo.com
  license: BSD2
  license_file: LICENSE
  summary: 'Support library for XMS libraries and products.'
  doc_url: 'https://aquaveo.github.io/xmscore/'
  dev_url: 'https://github.com/Aquaveo/xmscore'

extra:
  recipe-maintainers:
    - swainn
    - Tsubashi
    - gagelarsen
    - alemon-aquaveo
